fail_fast: true

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
               docs/.*|
               README.md
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
               docs/.*|
               README.md
          )$
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [ "--config", "pyproject.toml" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--settings-file", "pyproject.toml" ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0
    hooks:
      - id: upgrade-type-hints
